insert into item (id, name, price, image) values (1, 'Beige White Drawstring Shorts', 50, '/api/v1/image/1');
insert into item(id,name, price, image) values(2, 'Technicolor Striped Shirt', 30, '/api/v1/image/2');
insert into item(id,name, price, image) values(3, 'Mustard Hawaiian shirt', 200, '/api/v1/image/3');
insert into item(id,name, price, image) values(4, 'Kyoto Japan Graphic T', 170, '/api/v1/image/4');
insert into item(id,name, price, image) values(5, 'Cuffed Chinos', 500, '/api/v1/image/5');
insert into item(id,name, price, image) values(6, 'White Social Club Shorts', 210, '/api/v1/image/6');
insert into item(id,name, price, image) values(7, 'Woad Beach Style Shorts', 80, '/api/v1/image/7');
insert into item(id,name, price, image) values(8, 'Denim Dress Shirt', 200, '/api/v1/image/8');
insert into item(id,name, price, image) values(9, 'Black Button Down Shirt', 100, '/api/v1/image/9');
insert into item(id,name, price, image) values(10,'Blue/Grey Striped Dress Shirt', 250, '/api/v1/image/10');
insert into item(id,name, price, image) values(11,'Khaki Green Cordoroy Shirt', 300, '/api/v1/image/11');
insert into item(id,name, price, image) values(12,'Blue Washed Out Dress shirt', 50, '/api/v1/image/12');
insert into item(id,name, price, image) values(13, 'Maroon Dress Shirt', 300, '/api/v1/image/13');
insert into item(id,name, price, image) values(14 , 'Black Dress Shirt', 75,'/api/v1/image/14');
insert into item(id,name, price, image) values(15, 'White Linen Shirt', 250, '/api/v1/image/15');