insert into item (id, name, price, image) values (1, 'Supreme Jersey White', 50, '/api/v1/image/1');
insert into item(id,name, price, image) values(2, 'Shorts Black', 30, '/api/v1/image/2');
insert into item(id,name, price, image) values(3, 'Vans Shoes Red', 200, '/api/v1/image/3');
insert into item(id,name, price, image) values(4, 'Converse Sneakers Black', 170, '/api/v1/image/4');
insert into item(id,name, price, image) values(5, 'Supreme Black Tee', 500, '/api/v1/image/5');
insert into item(id,name, price, image) values(6, 'Jeans Acid Wash', 210, '/api/v1/image/6');
insert into item(id,name, price, image) values(7, 'Black Hoodie', 80, '/api/v1/image/7');
insert into item(id,name, price, image) values(8, 'Blue Boot-Cut Jeans', 200, '/api/v1/image/8');
insert into item(id,name, price, image) values(9, 'Plain White Tee', 100, '/api/v1/image/9');
insert into item(id,name, price, image) values(10,'Red Summer Dress', 250, '/api/v1/image/10');
insert into item(id,name, price, image) values(11,'Blue Plaid Skirt', 300, '/api/v1/image/11');
insert into item(id,name, price, image) values(12,'Raincoat', 50, '/api/v1/image/12');
insert into item(id,name, price, image) values(13, 'Black Bomber Jacket retro', 300, '/api/v1/image/13');
insert into item(id,name, price, image) values(14 , 'Black Jeans', 75,'/api/v1/image/14');
insert into item(id,name, price, image) values(15, 'Nike Air Force One', 250, '/api/v1/image/15');